#!/bin/bash
#private key is to be given as 3rd argument.
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <openrc> <tag>"
    exit 1
fi

OPENRC=$1
TAG=$2

install_dependencies() {
    touch cleanup.log
    chmod 777 cleanup.log
    echo "Checking and installing necessary dependencies..."
    sudo apt update > cleanup.log
    sudo apt-get upgrade -y > cleanup.log
    if ! command -v python3 &> cleanup.log; then
        sudo apt-get install -y python3 > cleanup.log
    fi
    if ! command -v pip3 &> cleanup.log; then
        sudo apt-get install -y python3-pip > cleanup.log
    fi
    if ! command -v openstack &> cleanup.log; then
        sudo apt-get install -y python3-openstackclient > cleanup.log
    fi
    if ! command -v ansible &> cleanup.log; then
        sudo add-apt-repository --yes --update ppa:ansible/ansible > cleanup.log
        sudo apt-get install -y ansible > cleanup.log
    fi
    if ! dpkg-query -W -f='${Status}' software-properties-common 2>cleanup.log | grep -q "ok installed"; then
        sudo apt-get install -y software-properties-common > cleanup.log
    fi
    pip3 install python-openstackclient argparse subprocess32 python-openstacksdk > cleanup.log
}


# Function to set up permissions
setup_permissions() {
    chmod 777 scripts/cleanup.py
}

# Function to invoke the Python script
invoke_python_script() {
    source $OPENRC
    echo "sourced $OPENRC"
    python3 scripts/cleanup.py $OPENRC $TAG || exit 1
}

# Main script execution
install_dependencies
setup_permissions
invoke_python_script
