#!/bin/bash
#private key is to be given as 3rd argument.
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <openrc> <tag> <ssh_key>"
    exit 1
fi

OPENRC=$1
TAG=$2
SSH_KEY=$3

# Function to check and install necessary dependencies
install_dependencies() {
    # Check and install software-properties-common
    if ! dpkg-query -W -f='${Status}' software-properties-common 2>/dev/null | grep -q "ok installed"; then
        echo "Installing software-properties-common..."
        sudo apt install -y software-properties-common
    else
        echo "software-properties-common already installed."
    fi

    # Check and install ansible
    if ! command -v ansible &> /dev/null; then
        echo "Installing ansible..."
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible
    else
        echo "ansible already installed."
    fi

    # Check and install Python 3.8.4
    PYTHON_VERSION=$(python3 --version 2>&1)
    if [[ "$PYTHON_VERSION" != "Python 3.8.4" ]]; then
        echo "Installing Python 3.8.4..."
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt update
        sudo apt install -y python3.8
        sudo apt install -y python3.8-venv python3.8-dev
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
    else
        echo "Python 3.8 already installed."
    fi

    # Ensure pip is up to date
    sudo apt install -y python3-pip
    pip3 install --upgrade pip

    # Install required Python packages
    pip3 install platformdirs
    pip3 install python-openstackclient argparse subprocess32 python-openstacksdk
}
# Function to set up permissions
setup_permissions() {
    chmod 777 scripts/operate.py
}
# Function to invoke the Python script

invoke_python_script() {
    source $OPENRC
    echo "sourced $OPENRC"
    python3 scripts/operate.py $OPENRC $TAG $SSH_KEY || exit 1
}

# Main script execution
install_dependencies
setup_permissions
invoke_python_script

echo " operate phase complete"