#!/bin/bash
#private key is to be given as 3rd argument.
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <openrc> <tag> <ssh_key>"
    exit 1
fi

OPENRC=$1
TAG=$2
SSH_KEY=$3

install_dependencies() {
    touch operate.log
    chmod 777 operate.log
    echo "Checking and installing necessary dependencies..."
    sudo apt update > operate.log
    sudo apt-get upgrade -y > operate.log
    if ! command -v python3 &> operate.log; then
        sudo apt-get install -y python3 > operate.log
    fi
    if ! command -v pip3 &> operate.log; then
        sudo apt-get install -y python3-pip > operate.log
    fi
    if ! command -v openstack &> operate.log; then
        sudo apt-get install -y python3-openstackclient > operate.log
    fi
    if ! command -v ansible &> operate.log; then
        sudo add-apt-repository --yes --update ppa:ansible/ansible > operate.log
        sudo apt-get install -y ansible > operate.log
    fi
    if ! dpkg-query -W -f='${Status}' software-properties-common 2>operate.log | grep -q "ok installed"; then
        sudo apt-get install -y software-properties-common > operate.log
    fi
    pip3 install python-openstackclient argparse subprocess32 python-openstacksdk > operate.log
}


# Function to set up permissions
setup_permissions() {
    chmod 777 scripts/operate.py
}
# Function to invoke the Python script

invoke_python_script() {
    source $OPENRC
    echo "sourced $OPENRC"
    python3 scripts/operate.py $OPENRC $TAG $SSH_KEY || exit 1
}

# Main script execution
install_dependencies
setup_permissions
invoke_python_script

echo " operate phase complete"